config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'portfolio', to: 'pages#portfolio', as: :portfolio
  get 'contact', to: 'pages#contact', as: :contact

  root to: 'pages#home'

  resources :contacts, only: [:new, :create]
    get 'contacts/new'
    get 'contacts/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  include MailForm::Delivery
  attribute :name, validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   validate: true
  attribute :nickname,  captcha: true

  def headers
    {
      subject: "Contact Form",
      to: "y.jsheahan@gmail.com",
      from: %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  require 'mail_form'

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
  redirect_to contacts_new_path, notice: 'Message sent successfully'
    else
      flash.now[:error] = 'Cannot send message'
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def portfolio
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<%= render "shared/navbar" %>

<div class="contact-container">

  <h4>
    CONTACT
  </h4>

  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, maxime distinctio assumenda labore quos sapiente dolorum expedita beatae voluptate odit!
  </p>

  <%= form_for @contact do |f| %>
    <% if flash[:error].present? %>
        <p> flash[:error]</p>
    <% end %>
    <%= f.label :name %> <br>
    <%= f.text_field :name, required: true %>

    <br>
    <%= f.label :email %> <br>
    <%= f.text_field :email, required: true %>

    <br>
    <%= f.label :message %> <br>
    <%= f.text_area :message, as: :text %>


    <%= f.label :nickname, style: "display: none" %> <br>
    <%= f.text_field :nickname, style: "display: none", hint: 'leave this field blank' %>


    <%= f.submit 'SEND', class: "button" %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yasmin Jones Sheahan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:wght@400;800&family=Noto+Sans:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
    <%= render "shared/footer" %>
<!--     <script src="portfolio.js"></script>
 -->
  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

  <script>
    AOS.init({
  // Global settings:
  // disable: false, // accepts following values: 'phone', 'tablet', 'mobile', boolean, expression or function
  // startEvent: 'DOMContentLoaded', // name of the event dispatched on the document, that AOS should initialize on
  // initClassName: 'aos-init', // class applied after initialization
  // animatedClassName: 'aos-animate', // class applied on animation
  // useClassNames: false, // if true, will add content of `data-aos` as classes on scroll
  // disableMutationObserver: false, // disables automatic mutations' detections (advanced)
  // debounceDelay: 50, // the delay on debounce used while resizing window (advanced)
  // throttleDelay: 99, // the delay on throttle used while scrolling the page (advanced)


  // Settings that can be overridden on per-element basis, by `data-aos-*` attributes:
  offset: 120, // offset (in px) from the original trigger point
  delay: 400, // values from 0 to 3000, with step 50ms
  duration: 1200, // values from 0 to 3000, with step 50ms
  easing: 'ease', // default easing for AOS animations
  once: false, // whether animation should happen only once - while scrolling down
  mirror: true, // whether elements should animate out while scrolling past them
  anchorPlacement: 'top', // defines which position of the element regarding to window should trigger the animation

});
  </script>
  </body>

</html>

app/views/pages/contact.html.erb
<%= render "shared/navbar" %>

<div class="contact-container">

  <h4>
    CONTACT
  </h4>

  <p id="fade-in">
    To get in touch with Yasmin, please fill out the form below and she will get back to you within 2 business days.
  </p>


  <form
    action="https://formspree.io/mrgyadgj"
    method="POST">

    <label id="fade-in">
      NAME
    </label>
    <input type="text" name="name">

    <label id="fade-in">
      EMAIL
    </label>
    <input type="email" name="_replyto">

    <label id="fade-in">
      MESSAGE
    </label>
    <input type="text" name="message" id="message-box">
    <div class="button-container">
      <input type="submit" value="Send" id="fade-in">
    </div>

  </form>

</div>
<script>
  const animatedTags = document.querySelectorAll("#fade-in")

  // fade out on load
  animatedTags.forEach(tag => {
    tag.style.opacity = 0
  })

  const fadeIn = function () {
    // look through all the animated tags and see
    // with the getBoundingClientRect() if it's in the window
    let delay = 0.6

    animatedTags.forEach(tag => {
      const tagTop = tag.getBoundingClientRect().top
      const tagBottom = tag.getBoundingClientRect().bottom

      if (tagTop < window.innerHeight && tagBottom > 0) {
        tag.style.animation = `fadeIn 1s ${delay}s both`
        delay = delay + 0.3
      } else {
        tag.style.opacity = 0
        tag.style.animation = ""
      }
    })
  }
   // on load, fade in
  fadeIn();

  document.addEventListener("scroll", function () {
    fadeIn();
  })

  // on browser resize, run fadeIn
  window.addEventListener("resize", function () {
    fadeIn();
  })
</script>

app/views/pages/home.html.erb
<div class="homepage-container">
  <div class="left-scene">
    <div class="logo">
    </div>

    <nav data-aos="fade-in">
      <%= link_to "ABOUT", root_path, class: "active" %>
      <%= link_to "PORTFOLIO", portfolio_path %>
      <%= link_to "CONTACT", contact_path %>
    </nav>

    <div class="homepage-text">
      <h1 data-aos="fade-in">
        Yasmin
        <br />
        Jones Sheahan
      </h1>

      <p data-aos="fade-in">
        Professional Dancer.
        <br />
        Aspiring Choreographer.
        <br />
        Based in London.
      </p>

      <div class="social-links" style="text-align: left;">
          <a href="https://www.instagram.com/yasmin.mjs/"" style="padding: 0;"><i class="fab fa-instagram"></i></a>
          <a href="https://vimeo.com/"><i class="fab fa-vimeo-v"></i></a>
          <a href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a>
      </div>
    </div>
  </div>


  <div class="homepage-headshot">
  </div>

</div>

<div class="training-skills-container">
  <div class="bio-training-container">
    <div class="bio-container" >
      <h4>Biography</h4>
      <p data-aos="fade-in">
        An experienced, versatile dancer. Yasmin uses her strength to execute weighted, definite actions, while moving with control to showcase every texture. <br />With a strong Hip Hop foundation, she eases naturally into grounded movement, but loves to show intricacy and femininity with the art of Waacking.
         </p>
      </p>
    </div>

    <div class="training-container" data-aos="fade-in">

      <h4>
        Training
      </h4>
      <p>
        Runway House
      </p>
      <p>
        Ideas. Identity. Industry.
      </p>
      <p>
        Keep It Moving Intensive
      </p>
      <p>
        Alleyne Dance Intensive
      </p>
      <p>
        ZooSkool
      </p>
      <p>
        Pineapple Performing Arts School
      </p>

    </div>
  </div>

  <div class="skills-other-container" data-aos="fade-in">
    <div class="skills-container">
      <h4>
        Skills
      </h4>
      <p>
        Hip Hop
      </p>
      <p>
        House
      </p>
      <p>
        Popping
      </p>
      <p>
        Waacking
      </p>
      <p>
        Commercial
      </p>
      <p>
        Contemporary
      </p>
      <p>
        Heels
      </p>
    </div>

    <div class="other-container" data-aos="fade-in">
      <h4>
        Other
      </h4>
      <a id="pilates-link" href="https://pilates-with-yasmin.superhi.com/">
        <p>
          Pilates/Fitness Instructor
        </p>
      </a>
    </div>

  </div>
</div>

<div class="homepage-container-2">
  <div class="movement-image">
  </div>

  <div class="measurements-container" data-aos="fade-in">

    <h4>
      Measurements
    </h4>
    <p>
      Height: 5'4"
    </p>
    <p>
      Hair: Black, Mid-length, Curly
    </p>
    <p>
      Ethnicity: Mixed White and Black Caribbean
    </p>
    <p>
      Nationality: British
    </p>
    <p>
      Eyes: Brown
    </p>
    <p>
      Chest: 32"
    </p>
    <p>
      Waist: 28"
    </p>
    <p>
      Hips: 32"
    </p>
    <p>
      Dress: UK 8
    </p>
    <p>
      Shoe: UK 6
    </p>

  </div>

</div>
<script>
  const animatedTags = document.querySelectorAll("#fade-in")

  // fade out on load
  animatedTags.forEach(tag => {
    tag.style.opacity = 0
  })

  const fadeIn = function () {
    // look through all the animated tags and see
    // with the getBoundingClientRect() if it's in the window
    let delay = 0.6

    animatedTags.forEach(tag => {
      const tagTop = tag.getBoundingClientRect().top
      const tagBottom = tag.getBoundingClientRect().bottom

      if (tagTop < window.innerHeight && tagBottom > 0) {
        tag.style.animation = `fadeIn 1s ${delay}s both`
        delay = delay + 0.3
      } else {
        tag.style.opacity = 0
        tag.style.animation = ""
      }
    })
  }
   // on load, fade in
  fadeIn();

  document.addEventListener("scroll", function () {
    fadeIn();
  })

  // on browser resize, run fadeIn
  window.addEventListener("resize", function () {
    fadeIn();
  })
</script>

app/views/pages/portfolio.html.erb
<%= render "shared/navbar" %>
<div class="portfolio-page">
  <div class="portfolio-container">

    <div class="title" data-aos="fade-in">
      <h4>
        Portfolio
      </h4>
    </div>
    <div class="images" id="image-1" data-aos="fade-in" data-aos-delay="400s">
    </div>
    <div class="images" id="image-2" data-aos="fade-in">
    </div>
    <div class="images" id="image-3" data-aos="fade-in" data-aos-delay="400s">
    </div>
    <div class="images" id="image-4" data-aos="fade-in">
    </div>
    <div class="images" id="image-5" data-aos="fade-in" data-aos-delay="400s">
    </div>
    <div class="images" id="image-6" data-aos="fade-in">
    </div>
    <div class="images" id="image-7" data-aos="fade-in" data-aos-delay="400s">
    </div>
  </div>
</div>

<div class="overlay">
  <div class="cross"></div>
  <section>
  </section>

  <div class="arrows">
    <div class="prev" style="background-image: url('https://res.cloudinary.com/dpzjvi2w1/image/upload/v1593883728/prev_wsnzar.svg');"></div>
    <div class="next" style="background-image: url('https://res.cloudinary.com/dpzjvi2w1/image/upload/v1593883728/next_imvw7h.svg');"></div>
  </div>
</div>


<script>

  const nextTag = document.querySelector(".overlay .arrows .next");
  const prevTag = document.querySelector(".overlay .arrows .prev");

  const sectionTag = document.querySelector(".overlay section");
  const crossTag = document.querySelector(".overlay div.cross");
  const overlayTag = document.querySelector(".overlay");
  const portfolioPageTag = document.querySelector(".portfolio-page");
  const firstPhoto = document.querySelector(".portfolio-page .portfolio-container .images#image-1");
  const secondPhoto = document.querySelector(".portfolio-page .portfolio-container .images#image-2");
  const thirdPhoto = document.querySelector(".portfolio-page .portfolio-container .images#image-3");
  const fourthPhoto = document.querySelector(".portfolio-page .portfolio-container .images#image-4");
  const fifthPhoto = document.querySelector(".portfolio-page .portfolio-container .images#image-5");
  const sixthPhoto = document.querySelector(".portfolio-page .portfolio-container .images#image-6");
  const seventhPhoto = document.querySelector(".portfolio-page .portfolio-container .images#image-7");


  const photos = [
    {
      image: "url('https://res.cloudinary.com/dpzjvi2w1/image/upload/v1593368061/yasminresize-4_bctit0.jpg')",
      id: "image-1"
    },
    {
      image: "url('https://res.cloudinary.com/dpzjvi2w1/image/upload/v1593368056/yasminresize-2_gdmmmw.jpg')",
      id: "image-2"
    },
    {
      image: "url('https://res.cloudinary.com/dpzjvi2w1/image/upload/v1593368051/Yasminresize-1_tjbv99.jpg')",
      id: "image-3"
    },
    { image: "url('https://res.cloudinary.com/dpzjvi2w1/image/upload/v1593368069/yasminresize-5_lyhs7r.jpg')",
     id: "image-4"
    },
    {
      image: "url('https://res.cloudinary.com/dpzjvi2w1/image/upload/v1593368117/yasminresize-6_gee7kb.jpg')",
      id: "image-5"
    },
    {
      image: "url('https://res.cloudinary.com/dpzjvi2w1/image/upload/v1593368122/yasminresize-7_djgjhz.jpg')",
      id: "image-6"
    },
    {
      image: "url('https://res.cloudinary.com/dpzjvi2w1/image/upload/v1593351669/Yasmin-RESIZE_cpfhih.jpg')",
      id: "image-7"
    }
  ]

  firstPhoto.addEventListener("click", function () {
    let photoNumber = 0;

    overlayTag.style.visibility = "visible";
    sectionTag.style.backgroundImage = photos[photoNumber].image;
    overlayTag.style.backgroundColor = "rgba(135, 161, 192, 0.6)"

  });

  secondPhoto.addEventListener("click", function () {
    let photoNumber = 1;
    overlayTag.style.visibility = "visible";
    sectionTag.style.backgroundImage = photos[photoNumber].image;
    overlayTag.style.backgroundColor = "rgba(135, 161, 192, 0.6)"

  });

  thirdPhoto.addEventListener("click", function () {
    let photoNumber = 2;
    overlayTag.style.visibility = "visible";
    sectionTag.style.backgroundImage = photos[photoNumber].image;
    overlayTag.style.backgroundColor = "rgba(135, 161, 192, 0.6)";


  });

  fourthPhoto.addEventListener("click", function () {
    let photoNumber = 3;

    overlayTag.style.visibility = "visible";
    sectionTag.style.backgroundImage = photos[photoNumber].image;
    overlayTag.style.backgroundColor = "rgba(227, 211, 202, 0.8)"

  })

  fifthPhoto.addEventListener("click", function () {
    let photoNumber = 4;

    overlayTag.style.visibility = "visible";
    sectionTag.style.backgroundImage = photos[photoNumber].image;
    overlayTag.style.backgroundColor = "rgba(227, 211, 202, 0.8)"

  })

  sixthPhoto.addEventListener("click", function () {
    let photoNumber = 5;

    overlayTag.style.visibility = "visible";
    sectionTag.style.backgroundImage = photos[photoNumber].image;
    overlayTag.style.backgroundColor = "rgba(227, 211, 202, 0.8)"

  })

  seventhPhoto.addEventListener("click", function () {
    let photoNumber = 6;

    overlayTag.style.visibility = "visible";
    sectionTag.style.backgroundImage = photos[photoNumber].image;
    overlayTag.style.backgroundColor = "rgba(227, 211, 202, 0.8)"

  })

  crossTag.addEventListener("click", function() {
    overlayTag.style.visibility = "hidden";
  })

  document.addEventListener("keyup", function (event) {
    if(event.key == "Escape") {
      overlayTag.style.visibility = "hidden";
    }
  })

</script>
<script>
  const animatedTags = document.querySelectorAll("#fade-in")

  // fade out on load
  animatedTags.forEach(tag => {
    tag.style.opacity = 0
  })

  const fadeIn = function () {
    // look through all the animated tags and see
    // with the getBoundingClientRect() if it's in the window
    let delay = 0.6

    animatedTags.forEach(tag => {
      const tagTop = tag.getBoundingClientRect().top
      const tagBottom = tag.getBoundingClientRect().bottom

      if (tagTop < window.innerHeight && tagBottom > 0) {
        tag.style.animation = `fadeIn 1s ${delay}s both`
        delay = delay + 0.3
      } else {
        tag.style.opacity = 0
        tag.style.animation = ""
      }
    })
  }
   // on load, fade in
  fadeIn();

  document.addEventListener("scroll", function () {
    fadeIn();
  })

  // on browser resize, run fadeIn
  window.addEventListener("resize", function () {
    fadeIn();
  })
</script>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>
    <i class="far fa-copyright"></i> Yasmin Jones Sheahan 2020
  </p>

  <p style="text-align: center;">
    Built with <i class="far fa-heart"></i> by YASMIN JONES SHEAHAN
  </p>

  <div class="social" style="text-align: right;">
    <%= render "shared/social_links" %>
<!--     <p>yasmin@yjs.co.uk</p> -->
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar" data-aos="fade-in">
  <%= link_to root_path do %>
    <div class="logo">
    </div>
  <% end %>


  <div class="menu">
    <nav>
      <% if controller_name == "pages" && action_name == "portfolio" %>
      <%= link_to "ABOUT", root_path %>
      <%= link_to "PORTFOLIO", portfolio_path, class: "active" %>
      <%= link_to "CONTACT", contact_path %>

      <% elsif controller_name == "pages" && action_name == "contact" %>
        <%= link_to "ABOUT", root_path %>
        <%= link_to "PORTFOLIO", portfolio_path %>
        <%= link_to "CONTACT", contact_path, class: "active" %>
      <% end %>
    </nav>
  </div>
</div>

app/views/shared/_social_links.html.erb
<div class="social-links">
    <a href="https://www.instagram.com/yasmin.mjs/"" style="padding: 0;"><i class="fab fa-instagram"></i></a>
    <a href="https://vimeo.com/"><i class="fab fa-vimeo-v"></i></a>
    <a href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a>
</div>